### PR TITLE
Ky np

### PR DESCRIPTION
**Pull request by KianYang-Lee**
Completed nb 1 ~ 3 . Ready to be reviewed.

### CODE REVIEW

**Comment by KianYang-Lee** [comment]
Completed all nbs. Ready to be merge if there are no addition or removal of content

**Comment by KianYang-Lee** [comment]
Added exercise nbs. Ready to merge if there are no feedbacks from @evanyeohboonkhai and @scot-certifai

**Review by scotgopal — APPROVED** [review]
Looks good.

**Review by evanyeohboonkhai — CHANGES_REQUESTED** [review]
All coding looks good to me except for some typo need to take care off: 

# 01 - NumPy ndarray

## Introduction to numpy ndarray

.....On the other hadn → should be on the other hand

# 03 - Basic Operations

## Notebook Description

.... block of numerical computational module. `numpy` → should be capital letter `Numpy`

**Comment by KianYang-Lee** [comment]
> All coding looks good to me except for some typo need to take care off:
> 
> # 01 - NumPy ndarray
> ## Introduction to numpy ndarray
> .....On the other hadn → should be on the other hand
> 
> # 03 - Basic Operations
> ## Notebook Description
> .... block of numerical computational module. `numpy` → should be capital letter `Numpy`

Fixed typo for "Hadn", got agreement that `numpy` is usable so not fixing that. TQ.

**Comment by evanyeohboonkhai** [comment]
ready to merged

**Pull request merged**
