### PR TITLE
Adding execution test workflow for Jupyter Notebook

### PR DESCRIPTION
**Pull request by fariskamaludin-skymind**
# Description

- Adding execution test for Jupyter Notebook using [Treon](https://pypi.org/project/treon/).
- Treon will run notebook top to bottom and flags execution errors if any.
- Tests were been separated based on solution & exercise folders, since we should expect execution error from exercise folders because of incomplete codes inside of it.

***Test for solution folders***
Screenshot 2021-06-04 at 2 20 33 PM

***Test for exercise folders***
image

- Can refer to this [workflow](https://github.com/CertifaiAI/basics-of-data-analytics/actions/runs/905148361) job as reference

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] Adding automation capabilities with GitHub Action

# Tested on?

- [ ] Windows
- [ ] Linux Ubuntu
- [ ] Centos
- [X] Mac
- [ ] Others  (State here -> xxx )

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by codenamewei** [comment]
ah allow me to ask a few questions

so we can see that these are failing in the solution workflow
Screenshot 2021-06-04 at 3 18 36 PM


but the result did still passed.
Screenshot 2021-06-04 at 3 19 37 PM


is there a way to determine the github actions to fail according to the failure in running jupyter notebook? 

cause if i imagine it .....
we should always make sure at least just for solution folder , all notebooks should run without problem

**Review by codenamewei — CHANGES_REQUESTED** [review]
also see how the workflow is install libraries needed to run the notebook
Screenshot 2021-06-04 at 3 22 16 PM


this method worries me 
1. always when not specifying the version, the installation will target the latest
hence in the long run things might break if the working version running the notebook is of older version
2. difficult for @fariskamaludin-skymind to grasp which libraries required to install to run notebook when the repo is huge

i also see how the repo do not have a config file to indicate which libraries which version required to run the notebook

preferably to have a config.yml in the repo provided by the developers
https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file 
that way faris can also refer to the config.yml for conda install 


@KianYang-Lee @scotgopal what do you think?

**Comment by fariskamaludin-skymind** [comment]
> ah allow me to ask a few questions
> 
> so we can see that these are failing in the solution workflow
> Screenshot 2021-06-04 at 3 18 36 PM
> 
> but the result did still passed.
> Screenshot 2021-06-04 at 3 19 37 PM
> 
> is there a way to determine the github actions to fail according to the failure in running jupyter notebook?
> 
> cause if i imagine it .....
> we should always make sure at least just for solution folder , all notebooks should run without problem

@codenamewei Actually, initially it can. However, once it detects error, the job will just immediately stop. Thus, causing the remaining notebooks not to be scanned. That's why I am putting the continue condition right in the workflow so that it can still continue scanning the other notebooks even it detects errors. This will give a broad overview which notebooks facing errors and which is not. I forgot to mention about this. 

Screenshot 2021-06-04 at 3 27 03 PM

**Comment by KianYang-Lee** [comment]
@codenamewei our team realized this insufficiency last week and are now working on a new PR for `environment.yml` file, most prob will be merged anytime now

**Comment by KianYang-Lee** [comment]
@codenamewei a new PR has been merged to include `environment.yml` with versioning.

**Comment by fariskamaludin-skymind** [comment]
@KianYang-Lee thank you. I will revise the workflow to build an environment based on the config file accordingly.

**Comment by codenamewei** [comment]
> > ah allow me to ask a few questions
> > so we can see that these are failing in the solution workflow
> > Screenshot 2021-06-04 at 3 18 36 PM
> > but the result did still passed.
> > Screenshot 2021-06-04 at 3 19 37 PM
> > is there a way to determine the github actions to fail according to the failure in running jupyter notebook?
> > cause if i imagine it .....
> > we should always make sure at least just for solution folder , all notebooks should run without problem
> 
> @codenamewei Actually, initially it can. However, once it detects error, the job will just immediately stop. Thus, causing the remaining notebooks not to be scanned. That's why I am putting the continue condition right in the workflow so that it can still continue scanning the other notebooks even it detects errors. This will give a broad overview which notebooks facing errors and which is not. I forgot to mention about this.
> 
> Screenshot 2021-06-04 at 3 27 03 PM

if i imagine it, 

solution workflow can be stop upon having failing use case
reason being solution notebook should be all passing, failing of use case force the PR owner to fix it prior to proceeding

for exercise workflow, it can be continue even though failing
because we know that exercise script are not complete by nature

**Comment by fariskamaludin-skymind** [comment]
> > > ah allow me to ask a few questions
> > > so we can see that these are failing in the solution workflow
> > > Screenshot 2021-06-04 at 3 18 36 PM
> > > but the result did still passed.
> > > Screenshot 2021-06-04 at 3 19 37 PM
> > > is there a way to determine the github actions to fail according to the failure in running jupyter notebook?
> > > cause if i imagine it .....
> > > we should always make sure at least just for solution folder , all notebooks should run without problem
> > 
> > 
> > @codenamewei Actually, initially it can. However, once it detects error, the job will just immediately stop. Thus, causing the remaining notebooks not to be scanned. That's why I am putting the continue condition right in the workflow so that it can still continue scanning the other notebooks even it detects errors. This will give a broad overview which notebooks facing errors and which is not. I forgot to mention about this.
> > Screenshot 2021-06-04 at 3 27 03 PM
> 
> if i imagine it,
> 
> solution workflow can be stop upon having failing use case
> reason being solution notebook should be all passing, failing of use case force the PR owner to fix it prior to proceeding
> 
> for exercise workflow, it can be continue even though failing
> because we know that exercise script are not complete by nature

Noted on that, I will change it accordingly for the solution workflow.

**Comment by fariskamaludin-skymind** [comment]
- Update the workflow to auto build conda environment alligned with the environment.yml
- Facing error in creating the environment as some of the conda's packages in the environment file are only available to the Windows OS
- Managed to solve the issue by changing the GitHub's runner OS to Windows instead of Ubuntu.
Screenshot 2021-06-07 at 10 36 45 AM

**Review by codenamewei — APPROVED** [review]
Looks good to me. @scotgopal If you can check this PR...
Feel free to raise questions.
If happens to approve, merge and delete the branch.

**Comment by scotgopal** [comment]
> * Update the workflow to auto build conda environment alligned with the environment.yml
> * Facing error in creating the environment as some of the conda's packages in the environment file are only available to the Windows OS
> * Managed to solve the issue by changing the GitHub's runner OS to Windows instead of Ubuntu.
> 
> Screenshot 2021-06-07 at 10 36 45 AM

Hi @fariskamaludin-skymind . Can I confirm if the `environment.yml` file here means that at the beginning of the workflow, it is building a new conda environment based on the  `environment.yml` file provided in this repo? If yes, then there could possibly be a bug somewhere because even though `auto-update-conda=false`, the workflow seems to still check for package versions (its updating the environment). You might have to take a look at it to further optimize this workflow.
image

Suggest to try putting `auto-update-conda=false` here. Maybe when it's explicitly put, it wouldn't auto-update. 😅 
image

**Comment by fariskamaludin-skymind** [comment]
Hi @scotgopal, from what I understand, `conda env update` command means that it will try to update the targeted env based on packages version from the targeted environment file. It might a little bit misleading from the log as it said ***Updating 'basics-of-data-analytics' env***. This is because it created the env first from command `activate-environment: basics-of-data-analytics` and then it updated the env with packages from the environment file. I don't think it tried to update the packages to the latest version.

Moreover, I think `auto-update-conda` command is updating the conda itself rather than updating the packages, I tested it as per your request. Hope I answered your question 😃 

image


image

**Comment by scotgopal** [comment]
Morning. Thanks for the clarification @fariskamaludin-skymind . Good to be clear about how the `auto-update-conda` is actually for updating conda itself. 

Coming back to the environment update, isn't it rather redundant for cross-checking the targeted env based on the targeted env file, when the targeted env was actually just built from the said env file? Is there a way to forgo this `conda.bat env update` process?

**Comment by fariskamaludin-skymind** [comment]
> Morning. Thanks for the clarification @fariskamaludin-skymind . Good to be clear about how the `auto-update-conda` is actually for updating conda itself.
> 
> Coming back to the environment update, isn't it rather redundant for cross-checking the targeted env based on the targeted env file, when the targeted env was actually just built from the said env file? Is there a way to forgo this `conda.bat env update` process?

@scotgopal Understood, I have tried to build the environment directly from the environment file, but seems like the library still force to create a new env called `test` (its default env).  If I linked it to environment file, it will just update the ***test*** env with the packages inside the environment file as previously.
image

**Comment by scotgopal** [comment]
> > Morning. Thanks for the clarification @fariskamaludin-skymind . Good to be clear about how the `auto-update-conda` is actually for updating conda itself.
> > Coming back to the environment update, isn't it rather redundant for cross-checking the targeted env based on the targeted env file, when the targeted env was actually just built from the said env file? Is there a way to forgo this `conda.bat env update` process?
> 
> @scotgopal Understood, I have tried to build the environment directly from the environment file, but seems like the library still force to create a new env called `test` (its default env). If I linked it to environment file, it will just update the _**test**_ env with the packages inside the environment file as previously.
> image

Interesting finding @fariskamaludin-skymind . As of now, we'll leave this optimization problem to rest. Will merge the changes now. Thanks for the great work! 💯

**Review by scotgopal — APPROVED** [review]
Workflow fulfils its objectives. Future optimization work can be done to reduce the validation time for a PR by skipping the `conda.bat env update...` step.

**Comment by fariskamaludin-skymind** [comment]
> Workflow fulfils its objectives. Future optimization work can be done to reduce the validation time for a PR by skipping the `conda.bat env update...` step.

@scotgopal I will start looking out for other option or method to reduce the validation time. Moreover, I have tried caching out the packages using [actions/cache](https://github.com/actions/cache), however the validation time became ~1-2 minutes longer. Not really sure whats happening as it retrieved the cache longer. Nevertheless, I will start monitoring this workflow if other issues arise.

**Pull request merged**
