### PR TITLE
Create 01 - Getting started with Pyplot.ipynb

### PR DESCRIPTION
**Pull request by evanyeohboonkhai**

### CODE REVIEW

**Comment by evanyeohboonkhai** [comment]
Hi team, please have a view of the format and code. @scot-certifai @jingzhi93 @KianYang-Lee

**Comment by evanyeohboonkhai** [comment]
@KianYang-Lee  @jingzhi93  @scot-certifai  Hi team, I have modified the notebook base on today morning meeting. Please have a view of it. Thanks

**Review by KianYang-Lee — COMMENTED** [review]
image
error in file path for nb 01

image
error in file path for nb 02

Also, the "train" folder can have better naming? for example "exercise"

**Comment by evanyeohboonkhai** [comment]
Done modification @KianYang-Lee

**Comment by evanyeohboonkhai** [comment]
Done modification @KianYang-Lee

**Comment by KianYang-Lee** [comment]
As per the naming convention, suggest to give Getting started with Matplotlib (exercise) a new number (maybe 02 instead of 01) so that the other folder comes in precedence to the exercise notebook.

**Comment by evanyeohboonkhai** [comment]
> As per the naming convention, suggest to give Getting started with Matplotlib (exercise) a new number (maybe 02 instead of 01) so that the other folder comes in precedence to the exercise notebook.

The

**Review by KianYang-Lee — APPROVED** [review]
Looks good to me.

**Pull request closed without merging**
